# Generated by Django 2.1.5 on 2019-02-22 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("contacts", "0002_auto_20190221_1132")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2019, 2, 22, 10, 47, 31, 677554, tzinfo=utc),
            ),
        )
    ]
